### PR TITLE
Implemented Rate Limiting and updated README

### PR DESCRIPTION
**Pull request by hankditton**

### CODE REVIEW

**Comment by intinig** [comment]
Hey, I finally reviewed your commits. I like them but could I ask you to change the way you use throttling?

From `:rate_limit_requests` and `:rate_limit_seconds` to `rate_limit: { requests: xx, seconds: xx }`

We'll also eventually move redis in a similar configuration pattern. Having the keys non nested worked before because we only had redis, but now that we have multiple unrelated configuration objects to pass, I think we need to namespace better.

Thx!

**Comment by hankditton** [comment]
Not a problem, I like it. I can also change the redis settings while I'm in there.

I'm going to try to work in the improvements to the rate-limit headers from this post: https://developer.riotgames.com/discussion/announcements/show/qTAtcMAa

It might take me a little while to get to this, but it is coming.

**Comment by intinig** [comment]
That's great news :)

**Comment by nicolaracco** [comment]
Hi @hankditton
Sorry for the delay, I checked your PR some days ago but after all this time there were a lot of conflicts due to the API upgrade. @fusillicode ported your work on the new API with the #64.
I just merged it and we'll release a new version during the day.

Thank you a lot and sorry again for the delay

**Comment by hankditton** [comment]
The delay is all my fault, sorry I never got around to wrapping this up. Thanks a lot for finishing this up @fusillicode!

**Comment by fusillicode** [comment]
There is no need to be sorry @hankditton! 😄

Btw it was really a pleasure for me to work on your feature. So, I'm the one who should be thankful! 😉

Cheers, buddy! 🍻

**Pull request closed without merging**
